package com.app.IVAS.Enum;

public enum PermissionTypeConstant {
    CREATE_USER,
    UPDATE_USER,
    DEFAULT,
    CAN_REQUEST_PLATE_NUMBER,
    CAN_APPROVE_PLATE_NUMBER,
    CAN_SELL_PLATE_NUMBER,
    CAN_RENEW_VEHICLE,
    CAN_PRINT_DOCUMENT,
    CAN_UPLOAD_STOCK,
    VIEW_MLA_STOCK,
    CAN_RAISE_OFFENSE,
}
